from peewee import *
from .Base import BaseModel

class Ticket(BaseModel):
    id = IntegerField()
    fecha = DateField()
    hora = TimeField()
    total = FloatField()
    tipo = CharField(max_length=255)
    documento = CharField(max_length=255)
    tid = IntegerField()
    puntosLealtad = CharField(max_length=255)
    correlativo = IntegerField()
    descuentoTotal = FloatField()
    propina = FloatField()
    descuentoLealtad = FloatField()
    servicioDomicilio = FloatField()
    cliente = CharField(max_length=255)
    mesa = CharField(max_length=255)
    anulado = CharField(max_length=255)
    mesero = CharField(max_length=255)
    companyUuid = CharField(max_length=255)
    docTipo = CharField(max_length=255)
    docTipoId = IntegerField()
    docId = CharField(max_length=255)
    numResolucion = CharField(max_length=255)
    docSerie = CharField(max_length=255)
    venEx = FloatField()
    venNoSuj = FloatField()
    venGrabLoc = FloatField()
    venCueTerNoDom = FloatField()
    anexoNum = IntegerField()
    nrc = CharField(max_length=255)
    nombre = CharField(max_length=255)
    dui = CharField(max_length=255)
    maqNum = CharField(max_length=45)
    venIntExNoSujProp = FloatField()
    expDenCA = FloatField()
    expFueCA = FloatField()
    expSer = FloatField()
    venZoFra = FloatField()
    tax = FloatField()

    class Meta:
        db_table = 'tickets'